# Generated by Django 3.2.13 on 2022-06-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('meters', models.FloatField()),
                ('centi_meters', models.FloatField()),
                ('foots', models.FloatField()),
                ('inches', models.FloatField()),
                ('bmi', models.FloatField()),
            ],
        ),
    ]
