# Generated by Django 3.2.13 on 2022-06-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmimodel',
            name='centi_meters',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bmimodel',
            name='foots',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bmimodel',
            name='inches',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bmimodel',
            name='meters',
            field=models.FloatField(null=True),
        ),
    ]
